### poista väärä id
DELETE http://localhost:3001/api/persons/668fe2b8cdebb131d34a0fes

### oikea id get
GET http://localhost:3001/api/persons/6694d8840830f51058f87b0f

### ei löydy
GET http://localhost:3001/api/persons/6694d8840830f51058f87b0a

### väärä muoto
GET http://localhost:3001/api/persons/6694d884

### liian lhyt nimi
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ka",
    "number": "123456"
}